[package]
name = "rust-ai-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
async-openai = "0.42.1"
dotenvy = "0.15.7"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.2", features = ["full"]}
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
